### ISSUE TITLE
Program crashes

### ISSUE THREAD

**Issue by ZaheenJ** [CarterT27/Terminal-Typing-Test#1]
Was in the middle of a typing test and it crashed:
Traceback (most recent call last):
  File "/home/zaheen/carter's_random_crap/Terminal-Typing-Test/main.py", line 196, in <module>
    wrapper(main)
  File "/usr/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/zaheen/carter's_random_crap/Terminal-Typing-Test/main.py", line 189, in main
    wpm_test(stdscr)
  File "/home/zaheen/carter's_random_crap/Terminal-Typing-Test/main.py", line 157, in wpm_test
    if ord(key) == 27: #If user hits escape key
TypeError: ord() expected a character, but string of length 13 found

**Comment by ZaheenJ** [comment]
Thanks for fixing, nice program btw
